#ifdef __HMISHAREMGR_H__
	#define HMISHAREMGR_VAR __declspec(dllexport)
#else
	#define HMISHAREMGR_VAR __declspec(dllimport)
#endif


#ifndef __HMISTRUCT_H__
#include "HMIStruct.h"
#endif

					;

/* 
	@ RDB FILE NAME CONST 정의 
								*/
// --------------------------------- RDB ---------------------------------------
//#define FILE_CENTERCODE				_T("RDB_CENTERCODE")
//#define SHARE_CENTERCODE			_T("RDB_SHARE_CENTERCODE")
#define SHARE_IDENTIFIEDOBJECT					_T("SHARE_COMMON_IDENTIFIEDOBJECT")
#define SHARE_GEOGRAPHICALREGION				_T("SHARE_COMMON_GEOGRAPHICALREGION")
#define SHARE_SUBGEOGRAPHICALREGION				_T("SHARE_COMMON_SUBGEOGRAPHICALREGION")
#define SHARE_DATAPOINTGROUPCODE				_T("SHARE_COMMON_DATAPOINTGROUPCODE")
#define SHARE_COMPUTERCODE						_T("SHARE_COMMON_COMPUTERCODE")
#define SHARE_PROGRAMCODE						_T("SHARE_COMMON_PROGRAMCODE")
#define SHARE_OPERATORCODE						_T("SHARE_COMMON_OPERATORCODE")
#define SHARE_SWITCHTYPECODE					_T("SHARE_COMMON_SWITCHTYPECODE")
#define SHARE_CONSTRUCTIONCODE					_T("SHARE_COMMON_CCONSTRUCTIONCODE")
#define SHARE_WAVECOMTYPE						_T("SHARE_COMMON_WAVECOMTYPE")
#define SHARE_STATEGROUP						_T("SHARE_COMMON_STATEGROUP")
#define SHARE_DATABYTE							_T("SHARE_COMMON_DATABYTE")
#define SHARE_STATESET							_T("SHARE_COMMON_STATESET")
#define SHARE_UNIT								_T("SHARE_COMMON_UNIT")
#define SHARE_SCALEFACTOR						_T("SHARE_COMMON_SCALEFACTOR")
#define SHARE_LIMITCODE							_T("SHARE_COMMON_LIMITCODE")
#define SHARE_LIMITSET							_T("SHARE_COMMON_LIMITSET")
#define SHARE_EQUIPCOMPANY						_T("SHARE_COMMON_EQUIPCOMPANY")
#define SHARE_SUBSTATION						_T("SHARE_COMMON_SUBSTATION")
#define SHARE_DISTRIBUTIONLINE					_T("SHARE_COMMON_DISTRIBUTIONLINE")
#define SHARE_BASEVOLTAGE						_T("SHARE_COMMON_BASEVOLTAGE")
#define SHARE_BASEPOWER							_T("SHARE_COMMON_BASEPOWER")
#define SHARE_VOLTAGELEVEL						_T("SHARE_COMMON_VOLTAGELEVEL")
#define SHARE_PHASE								_T("SHARE_COMMON_PHASE")
#define SHARE_PROTOCOLTYPE						_T("SHARE_COMMON_PROTOCOLTYPE")
#define SHARE_EQUIPMENTTYPE						_T("SHARE_COMMON_EQUIPMENTTYPE")
#define SHARE_RTUMAP							_T("SHARE_COMMON_RTUMAP")
#define SHARE_PSRTYPE							_T("SHARE_COMMON_PSRTYPE")
#define SHARE_COMMTYPE							_T("SHARE_COMMON_COMMTYPE")
#define SHARE_RTUTYPE							_T("SHARE_COMMON_RTUTYPE")
#define SHARE_CATEGORYCODE						_T("SHARE_COMMON_CATEGORYCODE")
#define SHARE_MEASURETYPEINFO					_T("SHARE_COMMON_MEASURETYPEINFO")
#define SHARE_DNPBIMAPINDEX						_T("SHARE_COMMON_DNPBIMAPINDEX")
#define SHARE_DNPBOMAPINDEX						_T("SHARE_COMMON_DNPBOMAPINDEX")
#define SHARE_DNPAIMAPINDEX						_T("SHARE_COMMON_DNPAIMAPINDEX")
#define SHARE_DNPAOMAPINDEX						_T("SHARE_COMMON_DNPAOMAPINDEX")
#define SHARE_DNPCOUNTERMAPINDEX				_T("SHARE_COMMON_DNPCOUNTERMAPINDEX")
#define SHARE_RTUDEVICE							_T("SHARE_COMMON_RTUDEVICE")
#define SHARE_CONDUCTINGEQUIPMENT				_T("SHARE_COMMON_CONDUCTINGEQUIPMENT")
#define SHARE_SWITCH							_T("SHARE_COMMON_SWITCH")
#define SHARE_ACLINESEGMENT						_T("SHARE_COMMON_ACLINESEGMENT")
#define SHARE_PERLENGTHSEQUENCEIMPEDANCE		_T("SHARE_COMMON_PERLENGTHSEQUENCEIMPEDANC")
#define SHARE_BUSBARSECTION						_T("SHARE_COMMON_BUSBARSECTION")
#define SHARE_COMPOSITESWITCH					_T("SHARE_COMMON_COMPOSITESWITCH")
#define SHARE_POWERTRANSFORMER					_T("SHARE_COMMON_POWERTRANSFORMER")
#define SHARE_TRANSFORMERWINDING				_T("SHARE_COMMON_TRANSFORMERWINDING")
#define SHARE_TAPCHANGER						_T("SHARE_COMMON_TAPCHANGER")
#define SHARE_TAPREGULATIONSCHEDULE				_T("SHARE_COMMON_TAPREGULATIONSCHEDULE")
#define SHARE_PROTECTIONEQUIPMENT				_T("SHARE_COMMON_PROTECTIONEQUIPMENT")
#define SHARE_RECLOSESEQUENCE					_T("SHARE_COMMON_RECLOSESEQUENCE")
#define SHARE_CURRENTRELAY						_T("SHARE_COMMON_CURRENTRELAY")
#define SHARE_BATTERYSTORAGE					_T("SHARE_COMMON_BATTERYSTORAGE")
#define SHARE_GENERATINGUNIT					_T("SHARE_COMMON_GENERATINGUNIT")
#define SHARE_GENREGULATIONSCHEDULE				_T("SHARE_COMMON_GENREGULATIONSCHEDULE")
#define SHARE_WINDTURBINE						_T("SHARE_COMMON_WINDTURBINE")
#define SHARE_PHOTOVOLTAIC						_T("SHARE_COMMON_PHOTOVOLTAIC")
#define SHARE_GENUNITOPCOSTCURVE				_T("SHARE_COMMON_GENUNITOPCOSTCURVE")
#define SHARE_ENERGYCONSUMER					_T("SHARE_COMMON_ENERGYCONSUMER")
#define SHARE_SHUNTCOMPASATOR					_T("SHARE_COMMON_SHUNTCOMPASATOR")
#define SHARE_STATICVARCOMPENSATOR				_T("SHARE_COMMON_STATICVARCOMPENSATOR")
#define SHARE_POWERSYSTEMRESOURCE				_T("SHARE_COMMON_POWERSYSTEMRESOURCE")
#define SHARE_PSRTYPE							_T("SHARE_COMMON_PSRTYPE")
#define SHARE_EQUIPMENTCONTAINER				_T("SHARE_COMMON_EQUIPMENTCONTAINER")
#define SHARE_SYMBOL							_T("SHARE_COMMON_SYMBOL")
#define SHARE_DASDIAGRAMINFO					_T("SHARE_COMMON_DASDIAGRAMINFO")
#define SHARE_STATIONDIAGRAMINFO				_T("SHARE_COMMON_STATIONDIAGRAMINFO")
#define SHARE_DISCRETE							_T("SHARE_COMMON_DISCRETE")
#define SHARE_SETDISCRETE						_T("SHARE_COMMON_SETDISCRETE")
#define SHARE_MEASUREMENT						_T("SHARE_COMMON_MEASUREMENT")
#define SHARE_SETMEASUREMENT					_T("SHARE_COMMON_SETMEASUREMENT")
#define SHARE_ACCUMULATOR						_T("SHARE_COMMON_ACCUMULATOR")
#define SHARE_CALCULATION						_T("SHARE_COMMON_CALCULATION")
#define SHARE_POSITION							_T("SHARE_COMMON_POSITION")
#define SHARE_WATER								_T("SHARE_COMMON_WATER")
#define SHARE_ACM_APPGROUP						_T("SHARE_COMMON_ACM_APPGROUP")
#define SHARE_ACM_MAPINDEX						_T("SHARE_COMMON_ACM_MAPINDEX")
#define SHARE_ACM_TABLE							_T("SHARE_COMMON_ACM_TABLE")
#define SHARE_ACM_TABLEGROUP					_T("SHARE_COMMON_ACM_TABLEGROUP")
#define SHARE_PCS								_T("SHARE_COMMON_PCS")
#define SHARE_MAINTRANSFORMER					_T("SHARE_COMMON_MAINTRANSFORMER")
#define SHARE_VIRTUAL_LINE						_T("SHARE_COMMON_VIRTUAL_LINE")

#define SHARE_MEMO								_T("SHARE_OPR_MEMO")
#define SHARE_MESSAGE							_T("SHARE_OPR_MESSAGE")
#define SHARE_CONSTRUCTION						_T("SHARE_OPR_CONSTRUCTION")
#define SHARE_OPERATORASSIGN					_T("SHARE_OPR_OPERATORASSIGN")
#define SHARE_WAVE_LIST							_T("SHARE_OPR_WAVE_LIST")
#define SHARE_WAVE_FILE							_T("SHARE_OPR_WAVE_FILE")
#define SHARE_COMPUTERSTATUS					_T("SHARE_OPR_COMPUTERSTATUS")
#define SHARE_CALCULATION_RESULT				_T("SHARE_OPR_CALCULATION_RESULT")

//------------------------------------------------------------------------------
// Purpose:  공유메모리 관리에 필요한 메모리 Share Memory Pointer
//------------------------------------------------------------------------------
HMISHAREMGR_VAR	ST_HMI_PROJECT						*g_pHMIProject;		

//------------------------------------------------------------------------------
// Purpose:  MG-EMS Rdb 항목에 대한 메모리 Share Memory Pointer
//------------------------------------------------------------------------------
//HMISHAREMGR_VAR	ST_RDB_CENTERCODE				*g_pRDBCenterCode;

HMISHAREMGR_VAR	ST_COMMON_IDENTIFIEDOBJECT			*g_pCommonIDENTIFIEDOBJECT;	
HMISHAREMGR_VAR	ST_COMMON_GEOGRAPHICALREGION		*g_pCommonGEOGRAPHICALREGION;	
HMISHAREMGR_VAR	ST_COMMON_SUBGEOGRAPHICALREGION		*g_pCommonSUBGEOGRAPHICALREGION;
HMISHAREMGR_VAR	ST_COMMON_DATAPOINTGROUPCODE		*g_pCommonDATAPOINTGROUPCODE;	
HMISHAREMGR_VAR	ST_COMMON_COMPUTERCODE				*g_pCommonCOMPUTERCODE;			
HMISHAREMGR_VAR	ST_COMMON_PROGRAMCODE				*g_pCommonPROGRAMCODE;			
HMISHAREMGR_VAR	ST_COMMON_OPERATORCODE				*g_pCommonOPERATORCODE;			
HMISHAREMGR_VAR	ST_COMMON_SWITCHTYPECODE			*g_pCommonSWITCHTYPECODE;		
HMISHAREMGR_VAR	ST_COMMON_CONSTRUCTIONCODE			*g_pCommonCONSTRUCTIONCODE;		
HMISHAREMGR_VAR	ST_COMMON_WAVECOMTYPE				*g_pCommonWAVECOMTYPE;			
HMISHAREMGR_VAR	ST_COMMON_STATEGROUP				*g_pCommonSTATEGROUP;			
HMISHAREMGR_VAR	ST_COMMON_DATABYTE					*g_pCommonDATABYTE;				
HMISHAREMGR_VAR	ST_COMMON_STATESET					*g_pCommonSTATESET;				
HMISHAREMGR_VAR	ST_COMMON_UNIT						*g_pCommonUNIT;					
HMISHAREMGR_VAR	ST_COMMON_SCALEFACTOR				*g_pCommonSCALEFACTOR;			
HMISHAREMGR_VAR	ST_COMMON_LIMITCODE					*g_pCommonLIMITCODE;			
HMISHAREMGR_VAR	ST_COMMON_LIMITSET					*g_pCommonLIMITSET;				
HMISHAREMGR_VAR	ST_COMMON_EQUIPCOMPANY				*g_pCommonEQUIPCOMPANY;			
HMISHAREMGR_VAR	ST_COMMON_SUBSTATION				*g_pCommonSUBSTATION;			
HMISHAREMGR_VAR	ST_COMMON_DISTRIBUTIONLINE			*g_pCommonDISTRIBUTIONLINE;		
HMISHAREMGR_VAR	ST_COMMON_BASEVOLTAGE				*g_pCommonBASEVOLTAGE;			
HMISHAREMGR_VAR	ST_COMMON_BASEPOWER					*g_pCommonBASEPOWER;			
HMISHAREMGR_VAR	ST_COMMON_VOLTAGELEVEL				*g_pCommonVOLTAGELEVEL;			
HMISHAREMGR_VAR	ST_COMMON_PHASE						*g_pCommonPHASE;				
HMISHAREMGR_VAR	ST_COMMON_PROTOCOLTYPE				*g_pCommonPROTOCOLTYPE;			
HMISHAREMGR_VAR	ST_COMMON_EQUIPMENTTYPE				*g_pCommonEQUIPMENTTYPE;		
HMISHAREMGR_VAR	ST_COMMON_RTUMAP					*g_pCommonRTUMAP;				
HMISHAREMGR_VAR	ST_COMMON_COMMTYPE					*g_pCommonCOMMTYPE;				
HMISHAREMGR_VAR	ST_COMMON_RTUTYPE					*g_pCommonRTUTYPE;				
HMISHAREMGR_VAR	ST_COMMON_CATEGORYCODE				*g_pCommonCATEGORYCODE;			
HMISHAREMGR_VAR	ST_COMMON_MEASURETYPEINFO			*g_pCommonMEASURETYPEINFO;		
HMISHAREMGR_VAR	ST_COMMON_DNPBIMAPINDEX				*g_pCommonDNPBIMAPINDEX;		
HMISHAREMGR_VAR	ST_COMMON_DNPBOMAPINDEX				*g_pCommonDNPBOMAPINDEX;		
HMISHAREMGR_VAR	ST_COMMON_DNPAIMAPINDEX				*g_pCommonDNPAIMAPINDEX;		
HMISHAREMGR_VAR	ST_COMMON_DNPAOMAPINDEX				*g_pCommonDNPAOMAPINDEX;		
HMISHAREMGR_VAR	ST_COMMON_DNPCOUNTERMAPINDEX		*g_pCommonDNPCOUNTERMAPINDEX;	
HMISHAREMGR_VAR	ST_COMMON_RTUDEVICE					*g_pCommonRTUDEVICE;			
HMISHAREMGR_VAR	ST_COMMON_CONDUCTINGEQUIPMENT		*g_pCommonCONDUCTINGEQUIPMENT;	
HMISHAREMGR_VAR	ST_COMMON_SWITCH					*g_pCommonSWITCH;				
HMISHAREMGR_VAR	ST_COMMON_ACLINESEGMENT				*g_pCommonACLINESEGMENT;	
HMISHAREMGR_VAR	ST_COMMON_PERLENGTHSEQUENCEIMPEDANCE *g_pCommonPERLENGTHSEQUENCEIMPEDANCE;
HMISHAREMGR_VAR	ST_COMMON_BUSBARSECTION				*g_pCommonBUSBARSECTION;		
HMISHAREMGR_VAR	ST_COMMON_COMPOSITESWITCH			*g_pCommonCOMPOSITESWITCH;		
HMISHAREMGR_VAR	ST_COMMON_POWERTRANSFORMER			*g_pCommonPOWERTRANSFORMER;		
HMISHAREMGR_VAR	ST_COMMON_TRANSFORMERWINDING		*g_pCommonTRANSFORMERWINDING;	
HMISHAREMGR_VAR	ST_COMMON_TAPCHANGER				*g_pCommonTAPCHANGER;	
HMISHAREMGR_VAR	ST_COMMON_TAPREGULATIONSCHEDULE		*g_pCommonTAPREGULATIONSCHEDULE;
HMISHAREMGR_VAR	ST_COMMON_PROTECTIONEQUIPMENT		*g_pCommonPROTECTIONEQUIPMENT;	
HMISHAREMGR_VAR	ST_COMMON_RECLOSESEQUENCE			*g_pCommonRECLOSESEQUENCE;		
HMISHAREMGR_VAR	ST_COMMON_CURRENTRELAY				*g_pCommonCURRENTRELAY;			
HMISHAREMGR_VAR	ST_COMMON_BATTERYSTORAGE			*g_pCommonBATTERYSTORAGE;		
HMISHAREMGR_VAR	ST_COMMON_GENERATINGUNIT			*g_pCommonGENERATINGUNIT;		
HMISHAREMGR_VAR	ST_COMMON_GENREGULATIONSCHEDULE		*g_pCommonGENREGULATIONSCHEDULE;
HMISHAREMGR_VAR	ST_COMMON_WINDTURBINE				*g_pCommonWINDTURBINE;			
HMISHAREMGR_VAR	ST_COMMON_PHOTOVOLTAIC				*g_pCommonPHOTOVOLTAIC;			
HMISHAREMGR_VAR	ST_COMMON_GENUNITOPCOSTCURVE		*g_pCommonGENUNITOPCOSTCURVE;	
HMISHAREMGR_VAR	ST_COMMON_ENERGYCONSUMER			*g_pCommonENERGYCONSUMER;	
HMISHAREMGR_VAR	ST_COMMON_SHUNTCOMPASATOR			*g_pCommonSHUNTCOMPASATOR;		
HMISHAREMGR_VAR	ST_COMMON_STATICVARCOMPENSATOR		*g_pCommonSTATICVARCOMPENSATOR;	
HMISHAREMGR_VAR	ST_COMMON_POWERSYSTEMRESOURCE		*g_pCommonPOWERSYSTEMRESOURCE;
HMISHAREMGR_VAR	ST_COMMON_PSRTYPE					*g_pCommonPSRTYPE;	
HMISHAREMGR_VAR	ST_COMMON_EQUIPMENTCONTAINER		*g_pCommonEQUIPMENTCONTAINER;	
HMISHAREMGR_VAR	ST_COMMON_SYMBOL					*g_pCommonSYMBOL;	
HMISHAREMGR_VAR	ST_COMMON_DASDIAGRAMINFO			*g_pCommonDASDIAGRAMINFO;	
HMISHAREMGR_VAR	ST_COMMON_STATIONDIAGRAMINFO		*g_pCommonSTATIONDIAGRAMINFO;
HMISHAREMGR_VAR	ST_COMMON_DISCRETE					*g_pCommonDISCRETE;				
HMISHAREMGR_VAR	ST_COMMON_SETDISCRETE				*g_pCommonSETDISCRETE;			
HMISHAREMGR_VAR	ST_COMMON_MEASUREMENT				*g_pCommonMEASUREMENT;			
HMISHAREMGR_VAR	ST_COMMON_SETMEASUREMENT			*g_pCommonSETMEASUREMENT;		
HMISHAREMGR_VAR	ST_COMMON_ACCUMULATOR				*g_pCommonACCUMULATOR;			
HMISHAREMGR_VAR	ST_COMMON_CALCULATION				*g_pCommonCALCULATION;
HMISHAREMGR_VAR	ST_COMMON_POSITION					*g_pCommonPOSITION;
HMISHAREMGR_VAR	ST_COMMON_WATER						*g_pCommonWATER;
HMISHAREMGR_VAR	ST_COMMON_ACM_APPGROUP				*g_pCommonACM_APPGROUP;
HMISHAREMGR_VAR	ST_COMMON_ACM_MAPINDEX				*g_pCommonACM_MAPINDEX;
HMISHAREMGR_VAR	ST_COMMON_ACM_TABLE					*g_pCommonACM_TABLE;
HMISHAREMGR_VAR	ST_COMMON_ACM_TABLEGROUP			*g_pCommonACM_TABLEGROUP;
HMISHAREMGR_VAR	ST_COMMON_PCS						*g_pCommonPCS;
HMISHAREMGR_VAR	ST_COMMON_MAINTRANSFORMER			*g_pCommonMAINTRANSFORMER;
HMISHAREMGR_VAR	ST_COMMON_VIRTUAL_LINE				*g_pCommonVIRTUAL_LINE;

HMISHAREMGR_VAR	ST_OPR_MEMO							*g_pOprMEMO;				
HMISHAREMGR_VAR	ST_OPR_MESSAGE						*g_pOprMESSAGE;			
HMISHAREMGR_VAR	ST_OPR_CONSTRUCTION					*g_pOprCONSTRUCTION;		
HMISHAREMGR_VAR	ST_OPR_OPERATORASSIGN				*g_pOprOPERATORASSIGN;		
HMISHAREMGR_VAR	ST_OPR_WAVE_LIST					*g_pOprWAVE_LIST;			
HMISHAREMGR_VAR	ST_OPR_WAVE_FILE					*g_pOprWAVE_FILE;			
HMISHAREMGR_VAR	ST_OPR_COMPUTERSTATUS				*g_pOprCOMPUTERSTATUS;		
HMISHAREMGR_VAR	ST_OPR_CALCULATION_RESULT			*g_pOprCALCULATION_RESULT;


// Rdb memory 생성 그리고 로딩
extern "C" int					APIENTRY HMISHARE_CREATE();
extern "C" int					APIENTRY HMISHARE_ALLOC_RDBMEM(TCHAR* tRdbFileName, DWORD dwRecordCnt);
extern "C" int					APIENTRY HMISHARE_REALLOC_RDBMEM(TCHAR* tRdbFileName, DWORD dwRecordCnt);
extern "C" void					APIENTRY HMISHARE_INDEX_MEM();
extern "C" int					APIENTRY HMISHARE_INSERT_MEM(TCHAR* tRdbFileName, int idx, CStringArray *strArray);
// Rdb memory open
extern "C" int					APIENTRY HMISHARE_OPEN_RDBMEM();
extern "C" int					APIENTRY HMISHARE_CLOSE();
extern "C" int					APIENTRY HMISHARE_DESTROY();
// 전체 rdb 관련
extern "C" int					APIENTRY HMISHARE_GET_STRUCTSIZE(TCHAR* tFileName);
extern "C" int					APIENTRY HMISHARE_GET_MAXRECORD(TCHAR* tFileName);
extern "C" int					APIENTRY HMISHARE_GET_RDBRECORDCOUNT(TCHAR* tFileName);
extern "C" ST_HMI_PROJECT*		APIENTRY HMISHARE_GET_PROJECT();
extern "C" void*				APIENTRY HMISHARE_GET_DATA(TCHAR *tFileName, int nIndex);
// 로그인 rdb 관련
//extern "C" ST_RDB_OPERATOR*		APIENTRY HMISHARE_GET_OPERATOR();
//extern "C" ST_RDB_OPERATOR*		APIENTRY HMISHARE_GET_OPERATORIDX(UINT nIndex);
//
//extern "C" ST_RDB_REMOTEUNIT*	APIENTRY HMISHARE_GET_PDBREMOTEUNIT();
//extern "C" ST_RDB_REMOTEUNIT*	APIENTRY HMISHARE_GET_PDBREMOTEUNITIDX(UINT nIndex);
//extern "C" ST_RDB_CONDUCTINGEQUIPMENT*	APIENTRY HMISHARE_GET_PDBCONDUCTINGEQUIPMENT();
//extern "C" ST_RDB_CONDUCTINGEQUIPMENT*	APIENTRY HMISHARE_GET_PDBCONDUCTINGEQUIPMENTIDX(UINT nIndex);


// 포인트별 정보 조회
//extern "C" ST_RDB_BIPOINT*		APIENTRY HMISHARE_GET_BIPOINT();
//extern "C" ST_RDB_BIPOINT*		APIENTRY HMISHARE_GET_BIPOINTIDX(UINT nMapId, UINT nIndex);
//
//extern "C" ST_RDB_BOPOINT*		APIENTRY HMISHARE_GET_BOPOINT();
//extern "C" ST_RDB_BOPOINT*		APIENTRY HMISHARE_GET_BOPOINTIDX(UINT nMapId, UINT nIndex);
//
//extern "C" ST_RDB_AIPOINT*		APIENTRY HMISHARE_GET_AIPOINT();
//extern "C" ST_RDB_AIPOINT*		APIENTRY HMISHARE_GET_AIPOINTIDX(UINT nMapId, UINT nIndex);
//
//extern "C" ST_RDB_AOPOINT*		APIENTRY HMISHARE_GET_AOPOINT();
//extern "C" ST_RDB_AOPOINT*		APIENTRY HMISHARE_GET_AOPOINTIDX(UINT nMapId, UINT nIndex);
//
//extern "C" ST_RDB_CNTPOINT*		APIENTRY HMISHARE_GET_CNTPOINT();
//extern "C" ST_RDB_CNTPOINT*		APIENTRY HMISHARE_GET_CNTPOINTIDX(UINT nMapId, UINT nIndex);
//
//extern "C" ST_PDB_STATEGROUP*	APIENTRY HMISHARE_GET_STATEGROUP();
//extern "C" ST_PDB_STATESET*		APIENTRY HMISHARE_GET_STATESET();

// etc
//extern "C" int					APIENTRY HMISHARE_REMOTEUNITID(int nDmcId);
//extern "C" int					APIENTRY HMISHARE_SAVEFILERTDATA(TCHAR* tFile, void* pVoid, DWORD dwSize);
//extern "C" int					APIENTRY HMISHARE_GET_EQIDTOREMOTEUNITID(int nEqid);
//extern "C" int					APIENTRY HMISHARE_GET_CEQIDTOPSRTYPE(int nEqid);
//extern "C" int					APIENTRY HMISHARE_GET_CPSIDTOPSRTYPE(int nEqid);
			
//extern "C" int					APIENTRY HMISHARE_LOAD_RDBMEM();
//extern "C" int					APIENTRY HMISHARE_LOAD_RDBMEMIDX(TCHAR* tRdbFileName);

//온라인 DB 실시간 PDB 업데이트
//extern "C" int					APIENTRY HMISHARE_UPDATE_PDBMEM(TCHAR* tPdbFile);